name: Node.js CI

on: 
  pull_request:
    branches: [ production, staging, development ]
  push:
    branches: [ production, staging, development ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 15

    - name: Install Dependencies
      run: npm install

    - name: ESLint
      run: npm run lint

    - name: install prettier
      run: npm install --save-dev prettier

    - name: Prettier
      run: npm run prettier

    - name: Test
      run: CI=true npm run test

    - name: Build
      run: npm run build
